"use strict";
var username = "Hi Asim Gohar Butt,";
var message = " 'I have started learning TYPESCRIPT'. ";
console.log(username, message);
var a = 21;
var b = 22;
var c = 24;
var d = 25;
var e = 26;
var f = 27;
var g = 28;
var h = 29;
var i = 30;
var j = 31;
var Substract = (a - b - c - d - e - f - g - h - i - j);
var Sum = (a + b + c + d + e + f + g + h + i + j);
var Multiply = (a * b * c * d * e * f * g * h * i * j);
var Divid = (a / b / c / d / e / f / g / h / i / j);
console.log(Substract);
console.log(Sum);
console.log(Multiply);
console.log(Divid);
